config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  post 'admin/leave_request'
  get 'admin/leave'
	resources :leaves
  resources :admin
  devise_scope :user do
    authenticated :user do
       get '/users/sign_out' => 'devise/sessions#destroy'
       root 'leaves#index', as: :authenticated_root
    end
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end	
end

app/views/layouts/shared/_footer.html.erb
<div class="navbar navbar-expand-lg navbar-light">
  <div class="text-center d-lg-none w-100">
    <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
      <i class="icon-unfold mr-2"></i>
      Footer
    </button>
  </div>
  <div class="navbar-collapse collapse" id="navbar-footer">
    <span class="navbar-text">
      &copy;
      <%= Date.today.cwyear %>. <a href="javascript:void(0);">Leave Management System</a> by <a href="javascript:void(0);">Avinash Kumar.</a>
    </span>
  </div>
  <h5><marquee behavior="scroll" direction="right" scrollamount="10">Leave Management System - Where Employees Leaves Can Easily Manage</marquee></h5>
</div>

app/views/layouts/shared/_normal_flash_messages.html.erb
<% if notice.present? %>
	<div class="alert alert-success alert-bordered alert-dismissible">
		<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
		<ul class="list list-square mb-0" style="-webkit-padding-start: 10px!important; -moz-padding-start: 10px!important; -ms-padding-start: 10px!important; -o-padding-start: 10px!important;">
			<li><%= notice %></li>
		</ul>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-danger alert-bordered alert-dismissible">
		<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
		<ul class="list list-square mb-0" style="-webkit-padding-start: 10px!important; -moz-padding-start: 10px!important; -ms-padding-start: 10px!important; -o-padding-start: 10px!important;">
			<li><%= alert %></li>
		</ul>
  </div>
<% end %>

app/views/layouts/shared/_object_flash_messages.html.erb
<% if object.present? %>
	<% if object.errors.any? %>
		<% if object.errors.full_messages.present? %>
		  <div class="alert alert-danger alert-bordered alert-dismissible">
				<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
				<ul class="list list-square mb-0" style="-webkit-padding-start: 10px!important; -moz-padding-start: 10px!important; -ms-padding-start: 10px!important; -o-padding-start: 10px!important;">
					<% object.errors.full_messages.each do |error_message| %>
						<li><%= error_message %></li>
					<% end %>
				</ul>
		  </div>
	  <% end %>
	<% end %>
<% end %>

app/views/layouts/shared/_page_header.html.erb
<div class="page-header page-header-light">
  <div class="page-header-content header-elements-md-inline">
    <div class="page-title d-flex">
      <% if current_user %>
        <% if current_user.role == "admin" %>
           <a href="<%= admin_index_path %>">
        <% end %>
        <% if current_user.role == "user" %>
           <a href="<%= leaves_path %>">
        <% end %>
      <% else %>
          <a href="/">
      <% end %> 
        <h4><i class="icon-users4 mr-2"></i><span class="font-weight-semibold">Leave Management</span> - System</h4>
        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
      </a>
    </div>
    <% if user_signed_in? %>
    <div class="header-elements d-none">
      <div class="d-flex justify-content-center">
        <% if current_user.role == "admin" %>
         <a href="/admin/leave" class="btn btn-link btn-float text-default"><i class="icon-user-plus text-primary"></i> <span>Leave Requests</span></a>
         <% end %>
        <ul class="navbar-nav">
          <li class="nav-item dropdown dropdown-user">
            <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                <%= image_tag "placeholder.jpg", class: "rounded-circle", alt: "placeholder.jpg" %>
              <% if user_signed_in? %>
                <span><%= current_user.try(:username) %></span>
              <% else %>
                <span>User Name</span>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <a href="<%= edit_user_registration_path %>" class="dropdown-item"><i class="icon-user"></i> Profile</a>
              <a href="<%= edit_user_registration_path %>" class="dropdown-item"><i class="icon-lock2"></i> Change Password</a>
              <div class="dropdown-divider"></div>
              <a href="<%= destroy_user_session_path %>" class="dropdown-item" data-method="DELETE"><i class="icon-switch2"></i> Logout</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <div class="header-elements d-none">
      <div class="d-flex justify-content-center">
        <!-- <a href="/users/sign_up" class="btn btn-link btn-float text-default"><i class="icon-user-plus text-primary"></i> <span>Sign Up</span></a> -->
        <a href="/users/sign_in" class="btn btn-link btn-float text-default"><i class="icon-users2 text-primary"></i> <span>Sign In</span></a>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div class="page-header page-header-light">
  <% if current_user %>
  <% if current_user.role == "admin" %>
    <div class="page-header-content header-elements-md-inline justify-content-center">
      <h4><i class="icon-user mr-2"></i><span class="font-weight-semibold">Admin</span> - Dashboard</h4>
    </div>
  <% end %>
  <% if current_user.role == "user" %>
    <div class="page-header-content header-elements-md-inline justify-content-center">
      <h4><i class="icon-user mr-2"></i><span class="font-weight-semibold">User</span> - Dashboard</h4>
    </div>
  <% end %> 
  <% end%> 
</div>