config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  post 'admin/leave_request'
  get 'admin/leave'
	resources :leaves
  resources :admin
  devise_scope :user do
    authenticated :user do
       get '/users/sign_out' => 'devise/sessions#destroy'
       root 'leaves#index', as: :authenticated_root
    end
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end	
end

app/views/admin/edit.html.erb
<!-- Centered forms -->
<div class="card-body">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <div class="header-elements-inline justify-content-center">
                <h5 class="card-title font-weight-semibold">Create User</h5>
              </div>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <%= form_with(method: :put, url: admin_path, local: true) do |form| %>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Email:</label>
                <div class="col-lg-9">
                  <input type="email" name="user[email]" value="<%= @user.email %>" class="form-control" placeholder="Email">
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Role:</label>
                <div class="col-lg-9">
                  <select class="form-control select" name="user[role]" data-fouc>
                    <option value="admin"<%="selected" if @user.role=="admin" %>>admin</option>
                    <option value="user" <%="selected" if @user.role=="user" %>>user</option>
                  </select>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Username:</label>
                <div class="col-lg-9">
                  <input type="text" name="user[username]" value="<%= @user.username %>" placeholder="User Name"class="form-control">
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Max Leave</label>
                <div class="col-lg-9">
                  <input type="number" name="user[max_leave]" value="<%= @user.max_leave %>" placeholder="Maximum Leave" class="form-control">
                </div>
              </div>
              <div class="text-right">
                <button type="submit" class="btn btn-primary">Update User<i class="icon-paperplane ml-2"></i></button>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<!-- Pagination types -->
<div class="card">
  <div class="card-header header-elements-inline ">
    <h5 class="card-title">User and Its Leave Details</h5>
		<div class="header-elements">
			<div class="list-icons">
				  <a href="/admin/new" class="btn btn-link btn-float text-default"><button type="button" class="btn btn-primary"><i class="icon-add mr-2"></i>Add User</button></a>
			</div>
		</div>
  </div>
  <div class="content">
    <table class="table datatable-pagination">
      <thead>
        <tr>
          <th>User Name</th>
          <th>Email</th>
          <th>Max Leave</th>
          <th>Role</th>
          <th>Created At</th>
          <th class="text-center">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |l| %>
        <tr>
          <td><%=l.username %></td>
          <td><%=l.email %></td>
          <td><%=l.max_leave %></td>
          <td><%=l.role %></td>
          <td><%=l.created_at %>        
          </td>
          <td class="text-center">
            <div class="list-icons">
              <div class="dropdown">
                <a href="#" class="list-icons-item" data-toggle="dropdown">
                  <i class="icon-menu9"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a href="<%= edit_admin_path(l) %>" class="dropdown-item"><i class="icon-pencil6"></i>Edit</a>
                  <a href="<%= admin_path(l) %>" class="dropdown-item"><i class="icon-eye4"></i>Show</a>
                  <a href="<%= admin_path(l) %>" data-confirm="Are you sure?"  data-method="delete" class="dropdown-item"><i class="icon-bin2"></i>Delete</a>
                </div>
              </div>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/leave.html.erb
<div class="tab-content">
  <div class="tab-pane fade show active" id="basic-tab3">
    <div class="card">
      <div class="content">
      <table class="table datatable-basic">
        <thead>
          <tr>
            <th>Leave Apply Date</th>
            <th>From Date</th>
            <th>To Date</th>
            <th>Reporting Head</th>
            <th>Reason</th>
            <th>Status</th>
            <th class="text-center">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @leaves.each do |l| %>
          <tr>
            <td><%=l.leave_apply.strftime("%^A, %d %^B %Y %I:%M %p") if l.leave_apply %></td>
            <td><%=l.leave_to.strftime("%^A, %d %^B %Y %I:%M %p") if l.leave_to %> </td>
            <td><%=l.leave_from.strftime("%^A, %d %^B %Y %I:%M %p") if l.leave_from %></td>
            <td><%=l.reporting_head %></td>
            <td><%=l.reason %></td>
            <td>
              <% if l.status == "applied" %>
                <span class="badge badge-info"><%=l.status %></span>
              <% end %>
              <% if l.status == "approved" %>
                <span class="badge badge-success"><%=l.status %></span>
              <% end %>
              <% if l.status == "rejected" %>
                <span class="badge badge-danger"><%=l.status %></span>
              <% end %>
            </td>
            <td class="text-center">
              <div class="list-icons">
                <div class="dropdown">
                  <a href="#" class="list-icons-item" data-toggle="dropdown">
                    <i class="icon-menu9"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right">
                    <a href="/admin/leave" onclick="return miniReport('<%= l.id%>', 'approved')" class="dropdown-item" ><i class="icon-thumbs-up2"></i>Approved</a>
                    <a href="/admin/leave" onclick="return miniReport('<%= l.id%>', 'rejected')" class="dropdown-item" ><i class="icon-thumbs-down2"></i>Reject</a>
                    <a href="<%= leafe_path(l) %>" data-confirm="Are you sure?"  data-method="delete" class="dropdown-item"><i class="icon-bin2"></i>Delete</a>
                  </div>
                </div>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  </div>
</div>
<script type="text/javascript">
function miniReport(id,status){
   $.ajax({
        url: "/admin/leave_request",
        timeout:30000,
        type: "POST",
        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
        data: {id: id, status: status },
     });
 };
</script>

app/views/admin/new.html.erb
<!-- Centered forms -->
<div class="card-body">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <div class="header-elements-inline justify-content-center">
                <h5 class="card-title font-weight-semibold">Create User</h5>
              </div>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <%= form_with(url: admin_index_path, local: true) do |form| %>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Email:</label>
                <div class="col-lg-9">
                  <input type="email" name="user[email]" class="form-control" placeholder="Email" required="true">
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Role:</label>
                <div class="col-lg-9">
                  <select class="form-control select" name="user[role]" data-fouc required="true">
                    <option value="admin">admin</option>
                    <option value="user">user</option>
                  </select>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Username:</label>
                <div class="col-lg-9">
                  <input type="text" name="user[username]" placeholder="User Name"class="form-control" required="true">
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Max Leave</label>
                <div class="col-lg-9">
                  <input type="number" name="user[max_leave]" placeholder="Maximum Leave" class="form-control" required="true">
                </div>
              </div>
              <div class="text-right">
                <button type="submit" class="btn btn-primary">Create User<i class="icon-paperplane ml-2"></i></button>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/show.html.erb
<!-- Centered forms -->
<div class="card-body">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <div class="header-elements-inline justify-content-center">
                <h5 class="card-title font-weight-semibold">Create User</h5>
              </div>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <%= form_with(method: :put, url: admin_path, local: true) do |form| %>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Email:</label>
                <div class="col-lg-9">
                  <input type="email" name="user[email]" value="<%= @user.email %>" class="form-control" readonly="true" placeholder="Email">
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Role:</label>
                <div class="col-lg-9">
                  <select class="form-control select" name="user[role]" disabled="true" data-fouc>
                    <option value="admin"<%="selected" if @user.role=="admin" %>>admin</option>
                    <option value="user" <%="selected" if @user.role=="user" %>>user</option>
                  </select>
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Username:</label>
                <div class="col-lg-9">
                  <input type="text" name="user[username]" value="<%= @user.username %>" readonly="true" placeholder="User Name"class="form-control">
                </div>
              </div>
              <div class="form-group row">
                <label class="col-lg-3 col-form-label">Max Leave</label>
                <div class="col-lg-9">
                  <input type="number" name="user[max_leave]" value="<%= @user.max_leave %>" readonly="true" placeholder="Maximum Leave" class="form-control">
                </div>
              </div>
              <% end %>
              <div class="text-center">
                 <a href="<%= admin_index_path %>"><button class="btn btn-primary">Back<i class="icon-paperplane ml-2"></i></button></a>
              </div>              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>